dataset:
  name: 'BEHAVE'
  annotation_file_train: 'data/datasets/behave_train_list.pkl'
  annotation_file_test: 'data/datasets/behave_test_list.pkl'
  with_aug_data: False
  init_cam_translation: [0, 0.75, 2]

train:
  num_workers: 16
  batch_size: 32
  max_epoch: 200
  drop_lr_at: 180
  trans_begin_epoch: 30
  output_dir: 'outputs/stackflow/behave/'
  resume: ''

eval:
  optim_steps: 150
  output_dir: 'outputs/stackflow/behave/'
  checkpoint: 'outputs/stackflow/behave/latest_checkpoint.pth'
  post_optim: False
