dataset:
  name: 'BEHAVE'
  annotation_file_train: 'data/datasets/behave_train_list.pkl'
  annotation_file_test: 'data/datasets/behave_test_list.pkl'
  annotation_file_aug: 'data/datasets/behave_aug_data_list.pkl'
  with_aug_data: True
  init_cam_translation: [0, 0.75, 2]

train:
  num_workers: 16
  batch_size: 32
  max_epoch: 200
  drop_lr_at: 180
  trans_begin_epoch: 30
  output_dir: 'outputs/stackflow/behave_aug/'

eval:
  optim_steps: 150
  post_optim: False
  output_dir: 'outputs/stackflow/behave_aug/'
  checkpoint: 'outputs/stackflow/behave_aug/latest_checkpoint.pth'
